export const devIcons = [
  { iconName: 'devicon-html5-plain', name: 'HTML' },
  { iconName: 'devicon-css3-plain', name: 'CSS' },
  { iconName: 'devicon-javascript-plain', name: 'JavaScript' },
  { iconName: 'devicon-typescript-original', name: 'TypeScript' },
  { iconName: 'devicon-nodejs-plain', name: 'Node.js' },
  { iconName: 'devicon-react-original', name: 'React.js' },
  { iconName: 'devicon-nextjs-original', name: 'Next.js' },
  { iconName: 'devicon-tailwindcss-plain', name: 'Tailwind CSS' },
  { iconName: 'devicon-npm-original-wordmark', name: 'NPM' },
  { iconName: 'devicon-wordpress-plain', name: 'WordPress' },
  { iconName: 'devicon-webpack-plain', name: 'Webpack' },
  { iconName: 'devicon-babel-original', name: 'Babel' },
  { iconName: 'devicon-git-plain', name: 'Git' },
  { iconName: 'devicon-graphql-plain', name: 'GraphQL' },
  { iconName: 'devicon-firebase-plain', name: 'Firebase' },
  { iconName: 'devicon-figma-plain', name: 'Figma' },
  { iconName: 'devicon-bootstrap-plain', name: 'Bootstrap' },
  { iconName: 'devicon-material-plain', name: 'Material UI' },
  { iconName: 'devicon-python-plain', name: 'Python' },
  { iconName: 'devicon-aws-plain', name: 'AWS' },
]
